### ISSUE TITLE
item cube recipes not working?

### ISSUE THREAD

**Issue by reguita** [Warren1001/ighe#2]
It is likely a user error but I cant get ANY of the Item Cube Recipes to work.

I tried purchasing items from vendors and finding them in game.

I cant get them to socket, change quality or upgrade.  Basically none of these recipes work for me.

So far everything else in read me is working.

## New Cube Recipes

- Item + El Rune = Item with 1 Socket
- Item + Eld Rune = Item with 2 Sockets

- Item + Hel Rune = Item with `item level = 99`

- Item + Perfect Skull = Item with Normal Quality
- Item + Perfect Diamond = Item with Superior Quality
- Item + Perfect Sapphire = Item with Magic Quality
- ...etc
- Item + Perfect Amethyst = Item with Unique Quality

To change the tier of an item, use a Perfect Ruby.
- Normal Item + Perfect Ruby = Exceptional Item
- Exceptional Item + Perfect Ruby = Elite Item

To make an item ethereal:
- Item + Zod Rune = Ethereal Item

**Comment by reguita** [comment]
Old recipes seem to work on the old code posted on llama's video:

https://www.youtube.com/watch?v=MyV9nFvV_7k

**Comment by Warren1001** [comment]
didn't see this til now, mustve missed the email about it.

not sure what to tell you, everyone else that has used this hasnt had any issues. i would try installing the mod from scratch again. be sure you delete the mod folder for this mod before installing the new one.

edit: so, after talking to him about it, items that spawn as white (from vendors or from drops) for some reason just dont like cube recipes. ill have to look into it.

**Comment by Jimmy-Z** [comment]
Is the number after the item name it's level? if yes, then the item level recipe is also not working, it makes a sound but the number doesn't change.

BTW I didn't use the unique charm and fast level to 99, I'm playing it _normally_, yes I suck, maybe the item level recipe is limited to player level?

**Comment by Warren1001** [comment]
ya theres some weirdness somewhere where depending on how you obtained the item recipes won't work on the item. so far it looks like if an item originated as blue, you can use all recipes. it seems to only impact items that first start as white. i havent looked into it yet

**Comment by Warren1001** [comment]
so i finally felt like looking into it and know how to fix it but its gonna be a lil tedious to fix so im not gonna do it immediately. ill get around to it when i add other QoL to the mod like all items are gamble-able and making crafting recipes easier to do and etc

**Comment by Warren1001** [comment]
k, i fixed this. download the new update
